apiVersion: v1
kind: Service
metadata:
  name: analytics
  namespace: subscriptio
  labels:
    app: analytics
spec:
  selector:
    app: analytics
  ports:
    - port: 8081
      targetPort: 8081
      protocol: TCP
  type: ClusterIP
